module: Bagbutik_Core
title: Bagbutik
author: Morten Bjerg Gregersen
source_host_url: https://github.com/MortenGregersen/Bagbutik
copyright: '© 2022 under [open source license](https://github.com/MortenGregersen/Bagbutik/blob/main/LICENSE).'
clean: true
exclude:
  - Sources/Bagbutik-Core/Models/*

custom_categories:
  - name: Service
    children:
    - BagbutikService
    - JWT
    - FetchData
    - ServiceError
  - name: Requests
    children:
    - Request
    - HTTPMethod
    - RequestBody
    - Parameters
    - EndpointParameter
    - AssociatedValueParameter
    - ParameterValue
    - FieldParameter
    - FilterParameter
    - IncludeParameter
    - ExistParameter
    - SortParameter
    - LimitParameter
  - name: Responses
    children:
    - EmptyResponse
    - PagedResponse
    - BinaryResponse
    - PlainTextResponse
  - name: Property Wrappers
    children:
    - NullCodable
