module: Bagbutik
author: Morten Bjerg Gregersen
github_url: https://github.com/MortenGregersen/Bagbutik
copyright: '© 2022 under [open source license](https://github.com/MortenGregersen/Bagbutik/blob/main/LICENSE).'
