version: 1
builder:
  configs:
  - platform: macos-xcodebuild
    scheme: Bagbutik
  - platform: macos-xcodebuild-arm
    scheme: Bagbutik
  - platform: ios
    scheme: Bagbutik
  - platform: tvos
    scheme: Bagbutik
  - platform: watchos
    scheme: Bagbutik
