ignore:
  - "Sources/Bagbutik-Core/Models"
  - "Sources/Bagbutik-Core/AnyCodingKey.swift"
  - "Sources/Bagbutik-Models/AppStore"
  - "Sources/Bagbutik-Models/GameCenter"
  - "Sources/Bagbutik-Models/Marketplaces"
  - "Sources/Bagbutik-Models/Provisioning"
  - "Sources/Bagbutik-Models/Reporting"
  - "Sources/Bagbutik-Models/TestFlight"
  - "Sources/Bagbutik-Models/Users"
  - "Sources/Bagbutik-Models/XcodeCloud"
  - "Sources/Bagbutik-Models/Extensions/*+PrettyName.swift"
  - "Sources/Bagbutik-AppStore"
  - "Sources/Bagbutik-GameCenter"
  - "Sources/Bagbutik-Marketplaces"
  - "Sources/Bagbutik-Provisioning"
  - "Sources/Bagbutik-Reporting"
  - "Sources/Bagbutik-TestFlight"
  - "Sources/Bagbutik-Users"
  - "Sources/Bagbutik-XcodeCloud"
  
