ignore:
  - "Tests"
  - "Sources/BagbutikCore/Models"
  - "Sources/BagbutikCore/AnyCodingKey.swift"
  - "Sources/BagbutikAppStoreModels"
  - "Sources/BagbutikGameCenterModels"
  - "Sources/BagbutikMarketplacesModels"
  - "Sources/BagbutikModelsShared"
  - "Sources/BagbutikProvisioningModels"
  - "Sources/BagbutikReportingModels"
  - "Sources/BagbutikTestFlightModels"
  - "Sources/BagbutikUsersModels"
  - "Sources/BagbutikWebhooksModels"
  - "Sources/BagbutikXcodeCloudModels"
  - "Sources/BagbutikAppStore"
  - "Sources/BagbutikGameCenter"
  - "Sources/BagbutikMarketplaces"
  - "Sources/BagbutikProvisioning"
  - "Sources/BagbutikReporting"
  - "Sources/BagbutikTestFlight"
  - "Sources/BagbutikUsers"
  - "Sources/BagbutikWebhooks"
  - "Sources/BagbutikXcodeCloud"
  
