import Bagbutik_Core
import Foundation

/**
 # DiagnosticSignature
 The data structure that represents the Diagnostic Signatures resource.

 Full documentation:
 <https://developer.apple.com/documentation/appstoreconnectapi/diagnosticsignature>
 */
public struct DiagnosticSignature: Codable, Identifiable {
    /// The opaque resource ID that uniquely identifies a diagnostic signature.
    public let id: String
    /// Navigational links that include the self-link.
    public var links: ResourceLinks?
    /// The resource type.
    public var type: String { "diagnosticSignatures" }
    /// Attributes that describe the diagnostic signature resource.
    public var attributes: Attributes?

    public init(id: String,
                links: ResourceLinks? = nil,
                attributes: Attributes? = nil)
    {
        self.id = id
        self.links = links
        self.attributes = attributes
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: AnyCodingKey.self)
        id = try container.decode(String.self, forKey: "id")
        links = try container.decodeIfPresent(ResourceLinks.self, forKey: "links")
        attributes = try container.decodeIfPresent(Attributes.self, forKey: "attributes")
        if try container.decode(String.self, forKey: "type") != type {
            throw DecodingError.dataCorruptedError(forKey: "type", in: container, debugDescription: "Not matching \(type)")
        }
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: AnyCodingKey.self)
        try container.encode(id, forKey: "id")
        try container.encodeIfPresent(links, forKey: "links")
        try container.encode(type, forKey: "type")
        try container.encodeIfPresent(attributes, forKey: "attributes")
    }

    /**
     # DiagnosticSignature.Attributes
     Attributes that describe a Diagnostic Signatures resource.

     Full documentation:
     <https://developer.apple.com/documentation/appstoreconnectapi/diagnosticsignature/attributes>
     */
    public struct Attributes: Codable {
        /// The diagnostic type.
        public var diagnosticType: DiagnosticType?
        public var insight: DiagnosticInsight?
        /// The name of the signature, generated by the system.
        public var signature: String?
        /// The signature weight, which indicates how critical an issue reported by the diagnostic signature is. Weight values are between 0 and 1.
        public var weight: Double?

        public init(diagnosticType: DiagnosticType? = nil,
                    insight: DiagnosticInsight? = nil,
                    signature: String? = nil,
                    weight: Double? = nil)
        {
            self.diagnosticType = diagnosticType
            self.insight = insight
            self.signature = signature
            self.weight = weight
        }

        public init(from decoder: Decoder) throws {
            let container = try decoder.container(keyedBy: AnyCodingKey.self)
            diagnosticType = try container.decodeIfPresent(DiagnosticType.self, forKey: "diagnosticType")
            insight = try container.decodeIfPresent(DiagnosticInsight.self, forKey: "insight")
            signature = try container.decodeIfPresent(String.self, forKey: "signature")
            weight = try container.decodeIfPresent(Double.self, forKey: "weight")
        }

        public func encode(to encoder: Encoder) throws {
            var container = encoder.container(keyedBy: AnyCodingKey.self)
            try container.encodeIfPresent(diagnosticType, forKey: "diagnosticType")
            try container.encodeIfPresent(insight, forKey: "insight")
            try container.encodeIfPresent(signature, forKey: "signature")
            try container.encodeIfPresent(weight, forKey: "weight")
        }

        public enum DiagnosticType: String, Codable, CaseIterable {
            case diskWrites = "DISK_WRITES"
            case hangs = "HANGS"
            case launches = "LAUNCHES"
        }
    }
}
