name: Check for new spec

on:
  schedule:
    - cron: '0 */12 * * *'

jobs:
  check:
    name: Check for new spec
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.0.0
    - name: Check for new spec
      run: ./check-spec-version.sh
      env:
        GH_TOKEN: ${{ secrets.BAGBUTIK_ACTIONS_TOKEN }}
