name: Check for new spec

on:
  schedule:
    - cron: '0 * * * *'

jobs:
  check:
    name: Check for new spec
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.0.0
    - uses: fwal/setup-swift@v1.14.0 # Until GitHub Actions has Swift >= 5.6 as default
    - name: Check for new spec
      run: ./check-spec-version.sh
      env:
        GH_TOKEN: ${{ secrets.BAGBUTIK_ACTIONS_TOKEN }}
