name: Check for new spec

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  check:
    name: Check for new spec
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Check for new spec
      run: ./check-spec-version.sh
      env:
        GH_TOKEN: ${{ secrets.BAGBUTIK_ACTIONS_TOKEN }}
