name: Docs

on:
  push:
    branches:
    - main

jobs:
  build:
    name: Build and Deploy
    runs-on: macos-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_16.2.app/Contents/Developer
    steps:
    - uses: actions/checkout@v4
    - name: Generate Documentation for Pages
      run: ./Documentation/generate_docs.sh
    - name: Add CNAME
      run: echo -n bagbutik.dev > docs/CNAME
    - name: Deploy to GitHub Pages
      uses: crazy-max/ghaction-github-pages@v4
      with:
        build_dir: "docs"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
