name: Documentation

on:
  push:
    branches: [ docs-setup ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: fwal/setup-swift@v1.14.0
      with:
        swift-version: "5.6.0"
    - name: Get swift version
      run: swift --version
    - name: Genereate DocC
      uses: fwcd/swift-docc-action@v1.0.1
      with:
        output: ./docs
        transform-static-hosting: true
    - name: Deploy to GitHub Pages
      uses: crazy-max/ghaction-github-pages@v2.6.0
      with:
        build_dir: ./docs
        fqdn: bagbutik.dev
        jekyll: false
